version: '3.9'

services:
  back:
    image: python:3.11.5
    build: 
      dockerfile: Sprint-1/meu_app_api/dockerfile
    ports:
      - "5000:5000"
    restart: always
    container_name: meu_app_api
    networks:
      - meu_app_net

  front:
    depends_on:
      - meu_app_api
    image: php:8.2-cli
    build: 
      dockerfile: Sprint-1/meu_app_front/dockerfile
    ports:
      - "8080:80"
      - "44301:443"
    restart: always
    container_name: meu_app_front
    networks:
      - meu_app_net

networks:
  meu_app_net: {}
